### ISSUE TITLE
flex 布局下，不能 autosize

### ISSUE THREAD

**Issue by ChenWeihua123** [ambit-tsai/echarts-for-vue#14]
flex 布局下，不能 autosize，有人遇到过这种情况吗
（图表容器 flex:1）

**Comment by ambit-tsai** [comment]
emmm，为什么不把Demo代码贴出来看看？

**Comment by ChenWeihua123** [comment]
<template>
    <div class="chart-container">
      <div style="height: 200px;border: 1px solid red;margin-bottom: 10px;flex-shrink: 0"></div>
      <div style="flex: 1 1 0;border: 1px solid purple">
        <cv-chart :option="option"></cv-chart>
      </div>
    </div>
</template>
<script>
import { defineComponent, onMounted, onBeforeUnmount, reactive, toRefs, inject } from 'vue';

export default defineComponent({
  components: {},
  props: {
    showQuery: {
      type: Boolean,
      default: true,
    },
  },
  setup() {
    const state = reactive({ option: {} });
    const query = reactive({});

    const setOption = () => {
      const option = {
				grid: {
					top: "20px",
					bottom: "30px",
					right: "10px",
					containLabel: true
				},
				xAxis: {
					type: "category",
					data: [],
					offset: 5,
					axisLine: {
						show: false
					},
					axisTick: {
						show: false
					}
				},
				yAxis: {
					type: "value",
					offset: 20,
					splitLine: {
						show: false
					},
					axisTick: {
						show: false
					},
					axisLine: {
						show: false
					}
				},
				tooltip: {
					trigger: "axis",
					formatter: comp => {
						const [serie] = comp;
						return `${serie.seriesName}：${serie.value}`;
					},
					axisPointer: {
						show: true,
						status: "shadow",
						z: -1,
						shadowStyle: {
							color: "#E6F7FF"
						},
						type: "shadow"
					},
					extraCssText: "width:120px; white-space:pre-wrap"
				},
				series: [
					{
						barWidth,
						name: "付款笔数",
						type: "bar",
						data: [],
						itemStyle: {
							color: "#4165d7"
						}
					},
					{
						type: "bar",
						barWidth,
						xAxisIndex: 0,
						barGap: "-100%",
						data: [],
						itemStyle: {
							color: "#f1f1f9"
						},
						zlevel: -1
					}
				]
      }
      
      option.xAxis.data = new Array(12).fill(1).map((e, i) => i + 1 + "月");
      option.series[0].data = new Array(12)
        .fill(1)
        .map(() => parseInt(Math.random() * 100));
      option.series[1].data = new Array(12).fill(100);

      state.option = option;
    };


    setOption();

    onMounted(() => {});
    onBeforeUnmount(() => {});

    return {
      ...toRefs(state),
      query,
    };
  },
});
</script>
<style lang="scss" scoped>
.chart-container {
  display: flex;
  flex-direction: column;
  padding: 16px;
  height: calc(100vh - 300px);
  border: 3px solid black;
}
</style>

@ambit-tsai

**Comment by ChenWeihua123** [comment]
<template>
    <div class="chart-container">
      <div style="height: 200px;border: 1px solid red;margin-bottom: 10px;flex-shrink: 0"></div>
      <div style="flex: 1 1 0;border: 1px solid purple">
        <cv-chart :option="option"></cv-chart>
      </div>
    </div>
</template>

**Comment by ChenWeihua123** [comment]
"""<template>
    <div class="chart-container">
      <div style="height: 200px;border: 1px solid red;margin-bottom: 10px;flex-shrink: 0"></div>
      <div style="flex: 1 1 0;border: 1px solid purple">
        <cv-chart :option="option"></cv-chart>
      </div>
    </div>
</template>
"""

**Comment by ChenWeihua123** [comment]
"""html
<template>
    <div class="chart-container">
      <div style="height: 200px;border: 1px solid red;margin-bottom: 10px;flex-shrink: 0"></div>
      <div style="flex: 1 1 0;border: 1px solid purple">
        <cv-chart :option="option"></cv-chart>
      </div>
    </div>
</template>
"""

**Comment by ChenWeihua123** [comment]
![image](https://user-images.githubusercontent.com/33150900/106986493-6c0dae00-67a6-11eb-8fc9-a13d345b6a64.png)

**Comment by ChenWeihua123** [comment]
<pre>
<template>
    <div class="chart-container">
      <div style="height: 200px;border: 1px solid red;margin-bottom: 10px;flex-shrink: 0"></div>
      <div style="flex: 1 1 0;border: 1px solid purple">
        <cv-chart :option="option"></cv-chart>
      </div>
    </div>
</template>
</pre>

**Comment by ChenWeihua123** [comment]
```
<template>
    <div class="chart-container">
      <div style="height: 200px;border: 1px solid red;margin-bottom: 10px;flex-shrink: 0"></div>
      <div style="flex: 1 1 0;border: 1px solid purple">
        <cv-chart :option="option"></cv-chart>
      </div>
    </div>
</template>
```
