### ISSUE TITLE
1.4.0 生产环境下报错。

### ISSUE THREAD

**Issue by gee1k** [ambit-tsai/echarts-for-vue#20]
首先，非常感谢作者的开源风险。
下午收到 dependentsbot 更新 echarts-for-vue。合并后 Github Action 自动部署到 vercel，领导刚打开看，所有图表全出不来了。🌚

麻烦修复一下，以免更多用户使用

![image](https://user-images.githubusercontent.com/12059800/119790748-c160fd00-bf06-11eb-97e8-0266637c8f2c.png)
![image](https://user-images.githubusercontent.com/12059800/119791246-3cc2ae80-bf07-11eb-94ab-7c811b3066fa.png)

**Comment by ambit-tsai** [comment]
还请提供能复现错误的相关信息

**Comment by gee1k** [comment]
不需要什么特殊的，生产环境就报错。
this.$data 是 undefined

**Comment by ambit-tsai** [comment]
this.$data 为 undefined 肯定是不正常的。
但是，我本地测试用例没有这样的问题，所以还请提供个复现的例子

**Comment by zzzttt1017** [comment]
> 不需要什么特殊的，生产环境就报错。
> this.$data 是 undefined

我也遇到了，不过是NodeJs新版本的问题，回退到V14.15.1就好了，具体原因不明

**Comment by linjianlin** [comment]
同样出错了，回退 Node 版本也不行，线下开发环境没问题，生产环境就报错

**Comment by ambit-tsai** [comment]
> 同样出错了，回退 Node 版本也不行，线下开发环境没问题，生产环境就报错

或是压缩导致的，能提供个复现 Demo 吗？

**Comment by linjianlin** [comment]
> > 同样出错了，回退 Node 版本也不行，线下开发环境没问题，生产环境就报错
> 
> 或是压缩导致的，能提供个复现 Demo 吗？

[Demo](https://github.com/linjianlin/echarts_demo)

**Comment by ambit-tsai** [comment]
初步定位为 Vue 3 Proxy 代理限制对 vm.$data 的访问，已在 v1.4.1 中修复 @gee1k @zzzttt1017 @linjianlin

**Comment by linjianlin** [comment]
> 初步定位为 Vue 3 Proxy 代理限制对 vm.$data 的访问，已在 v1.4.1 中修复 @gee1k @zzzttt1017 @linjianlin

线上环境正常了，感谢
