### ISSUE TITLE
registerMap为svg类型时，svg显示不正常

### ISSUE THREAD

**Issue by hxgqh** [ambit-tsai/echarts-for-vue#22]
采用官方示例：https://echarts.apache.org/examples/zh/editor.html?c=geo-svg-traffic

svg图只显示宽高的一半内容。

**Comment by ambit-tsai** [comment]
经测试，当组件设置的宽高比与 SVG 差不多时，未出现只显示一半宽高的情况。
```html
<ECharts style="width: 782px; height: 730px;" />
```

**Comment by ambit-tsai** [comment]
若上述回答未能解决你的问题，还请给个复现的 Demo
