### ISSUE TITLE
Cannot read property 'init' of undefined

### ISSUE THREAD

**Issue by callmesoul** [ambit-tsai/echarts-for-vue#8]
Cannot read property 'init' of undefined

echarts 5.0以上会报这个错,降到4.9就可以了

**Comment by ambit-tsai** [comment]
从报错来看，是`echarts`对象没有正确引进导致的。官方建议通过如下方式引进：
1. 使用 ES Module
```
import * as echarts from 'echarts';
```
2. 使用 CommonJS
```
const echarts = require('echarts');
```
详见 [官方文档](https://echarts.apache.org/next/zh/tutorial.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%9E%84%E5%BB%BA%20ECharts)
